name: Deploy to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: 'Checkout Code'
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: 'Login to Azure'
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8086D2D453464C6E902B51459E12FD8D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_61EF9076E5204303B6A0DD2844578555 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_35E42B52E64146C2979177478A7985C3 }}

      # Step 3: Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'assetanalysis'
          slot-name: 'Production'
