# Deploy Python app to Azure Web App
name: Build and deploy Python app to Azure Web App - assetanalysis

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - uses: actions/checkout@v4

      # Set up Python
      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Install system-level dependencies for ta-lib (required for Linux builds)
      - name: Install system dependencies for ta-lib
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential gcc make libta-lib-dev

      # Install Python dependencies
      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      # Login to Azure
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_EE620EA71AE54A349F5982E45313F78E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6EFF17126FDA407C87B0685C1FBCA2F3 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_450975241FE740FFAB61A658E2E676E0 }}

      # Deploy to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'assetanalysis' # Replace with your Azure Web App name
          slot-name: 'production' # Replace if you're using a different slot
          
